# Generated by Django 5.2.8 on 2025-11-17 18:54

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ForecastPeriod',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('forecast_date', models.DateField(help_text='Date this forecast is for')),
                ('period_start', models.DateTimeField(help_text='Start of forecast period')),
                ('period_end', models.DateTimeField(help_text='End of forecast period')),
                ('temperature', models.IntegerField(help_text='Temperature value', validators=[django.core.validators.MinValueValidator(-50), django.core.validators.MaxValueValidator(150)])),
                ('temperature_unit', models.CharField(choices=[('F', 'Fahrenheit'), ('C', 'Celsius')], default='F', max_length=1)),
                ('apparent_temperature', models.IntegerField(blank=True, help_text='Feels-like temperature', null=True, validators=[django.core.validators.MinValueValidator(-50), django.core.validators.MaxValueValidator(150)])),
                ('short_forecast', models.CharField(help_text='Brief forecast description', max_length=200)),
                ('detailed_forecast', models.TextField(blank=True, help_text='Detailed forecast text')),
                ('wind_speed', models.IntegerField(help_text='Wind speed in mph', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(200)])),
                ('wind_direction', models.CharField(blank=True, choices=[('N', 'North'), ('NE', 'Northeast'), ('E', 'East'), ('SE', 'Southeast'), ('S', 'South'), ('SW', 'Southwest'), ('W', 'West'), ('NW', 'Northwest')], max_length=2)),
                ('wind_gust', models.IntegerField(blank=True, help_text='Wind gust speed in mph', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(200)])),
                ('precipitation_probability', models.IntegerField(blank=True, help_text='Chance of precipitation as percentage', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('nws_data_url', models.URLField(blank=True, help_text='Source NWS API URL')),
                ('raw_data', models.JSONField(blank=True, help_text='Raw API response data', null=True)),
            ],
            options={
                'verbose_name': 'Forecast Period',
                'verbose_name_plural': 'Forecast Periods',
                'ordering': ['location', 'period_start'],
            },
        ),
        migrations.CreateModel(
            name='DailyForecast',
            fields=[
                ('forecastperiod_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='weather.forecastperiod')),
                ('high_temperature', models.IntegerField(blank=True, help_text='High temperature for the day', null=True, validators=[django.core.validators.MinValueValidator(-50), django.core.validators.MaxValueValidator(150)])),
                ('low_temperature', models.IntegerField(blank=True, help_text='Low temperature for the day', null=True, validators=[django.core.validators.MinValueValidator(-50), django.core.validators.MaxValueValidator(150)])),
            ],
            options={
                'verbose_name': 'Daily Forecast',
                'verbose_name_plural': 'Daily Forecasts',
                'ordering': ['location', 'forecast_date'],
            },
            bases=('weather.forecastperiod',),
        ),
        migrations.CreateModel(
            name='HourlyForecast',
            fields=[
                ('forecastperiod_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='weather.forecastperiod')),
                ('humidity', models.IntegerField(blank=True, help_text='Relative humidity percentage', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('dew_point', models.IntegerField(blank=True, help_text='Dew point temperature', null=True, validators=[django.core.validators.MinValueValidator(-50), django.core.validators.MaxValueValidator(100)])),
            ],
            options={
                'verbose_name': 'Hourly Forecast',
                'verbose_name_plural': 'Hourly Forecasts',
                'ordering': ['location', 'period_start'],
            },
            bases=('weather.forecastperiod',),
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Location name (e.g., 'Austin, TX')", max_length=200)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text='Latitude in decimal degrees', max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, help_text='Longitude in decimal degrees', max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('zip_code', models.CharField(blank=True, help_text='US ZIP code', max_length=10)),
                ('nws_office', models.CharField(blank=True, help_text='NWS forecast office', max_length=10)),
                ('grid_x', models.IntegerField(blank=True, help_text='NWS grid X coordinate', null=True)),
                ('grid_y', models.IntegerField(blank=True, help_text='NWS grid Y coordinate', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_forecast_update', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ForecastRequest',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_type', models.CharField(default='forecast', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('cached', 'Cached')], default='pending', max_length=20)),
                ('response_time_ms', models.IntegerField(blank=True, help_text='API response time in milliseconds', null=True)),
                ('cache_hit', models.BooleanField(default=False, help_text='Whether this was served from cache')),
                ('error_message', models.TextField(blank=True, help_text='Error details if request failed')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('locations_requested', models.ManyToManyField(related_name='forecast_requests', to='weather.location')),
            ],
            options={
                'verbose_name': 'Forecast Request',
                'verbose_name_plural': 'Forecast Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='forecastperiod',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecasts', to='weather.location'),
        ),
        migrations.CreateModel(
            name='WeatherAlert',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nws_alert_id', models.CharField(help_text='NWS Alert ID', max_length=100, unique=True)),
                ('event', models.CharField(help_text='Alert event type', max_length=200)),
                ('headline', models.CharField(help_text='Alert headline', max_length=500)),
                ('description', models.TextField(help_text='Full alert description')),
                ('severity', models.CharField(choices=[('minor', 'Minor'), ('moderate', 'Moderate'), ('severe', 'Severe'), ('extreme', 'Extreme')], max_length=20)),
                ('urgency', models.CharField(choices=[('immediate', 'Immediate'), ('expected', 'Expected'), ('future', 'Future'), ('past', 'Past'), ('unknown', 'Unknown')], max_length=20)),
                ('onset', models.DateTimeField(blank=True, help_text='Alert start time', null=True)),
                ('expires', models.DateTimeField(blank=True, help_text='Alert expiration time', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('raw_data', models.JSONField(blank=True, help_text='Raw NWS alert data', null=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='weather.location')),
            ],
            options={
                'verbose_name': 'Weather Alert',
                'verbose_name_plural': 'Weather Alerts',
                'ordering': ['-onset', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['name'], name='weather_loc_name_d20a81_idx'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['zip_code'], name='weather_loc_zip_cod_30c3ce_idx'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['created_by'], name='weather_loc_created_e2f3b7_idx'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['last_forecast_update'], name='weather_loc_last_fo_bdbe6e_idx'),
        ),
        migrations.AddIndex(
            model_name='forecastrequest',
            index=models.Index(fields=['user', 'created_at'], name='weather_for_user_id_195b65_idx'),
        ),
        migrations.AddIndex(
            model_name='forecastrequest',
            index=models.Index(fields=['status'], name='weather_for_status_182e9b_idx'),
        ),
        migrations.AddIndex(
            model_name='forecastrequest',
            index=models.Index(fields=['request_type'], name='weather_for_request_6836eb_idx'),
        ),
        migrations.AddIndex(
            model_name='forecastperiod',
            index=models.Index(fields=['location', 'forecast_date'], name='weather_for_locatio_eeaaea_idx'),
        ),
        migrations.AddIndex(
            model_name='forecastperiod',
            index=models.Index(fields=['period_start'], name='weather_for_period__660fd8_idx'),
        ),
        migrations.AddIndex(
            model_name='forecastperiod',
            index=models.Index(fields=['created_at'], name='weather_for_created_753d2a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='forecastperiod',
            unique_together={('location', 'period_start', 'period_end')},
        ),
        migrations.AddIndex(
            model_name='weatheralert',
            index=models.Index(fields=['location', 'is_active'], name='weather_wea_locatio_a4dec2_idx'),
        ),
        migrations.AddIndex(
            model_name='weatheralert',
            index=models.Index(fields=['onset'], name='weather_wea_onset_dfb288_idx'),
        ),
        migrations.AddIndex(
            model_name='weatheralert',
            index=models.Index(fields=['severity'], name='weather_wea_severit_7a4326_idx'),
        ),
    ]
