# Generated by Django 5.2.8 on 2025-11-17 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='forecastperiod',
            name='is_daytime',
            field=models.BooleanField(default=True, help_text='Whether this is a daytime forecast'),
        ),
    ]
