# Generated by Django 5.2.8 on 2025-11-17 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_forecastperiod_is_daytime'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='custom_name',
            field=models.CharField(blank=True, help_text='Custom display name for this location (optional)', max_length=200),
        ),
    ]
