# Generated by Django 5.2.8 on 2025-11-17 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0003_location_custom_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['display_order', 'name'], 'verbose_name': 'Location', 'verbose_name_plural': 'Locations'},
        ),
        migrations.AddField(
            model_name='location',
            name='display_order',
            field=models.IntegerField(default=0, help_text='Order for displaying locations'),
        ),
    ]
