# Generated by Django 5.2.8 on 2025-11-17 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0004_alter_location_options_location_display_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='current_conditions',
            field=models.CharField(blank=True, help_text='Current weather conditions', max_length=200),
        ),
        migrations.AddField(
            model_name='location',
            name='current_humidity',
            field=models.IntegerField(blank=True, help_text='Current humidity percentage', null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='current_temp',
            field=models.IntegerField(blank=True, help_text='Current temperature', null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='current_wind_direction',
            field=models.CharField(blank=True, help_text='Current wind direction', max_length=10),
        ),
        migrations.AddField(
            model_name='location',
            name='current_wind_speed',
            field=models.IntegerField(blank=True, help_text='Current wind speed in mph', null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='last_observation_time',
            field=models.DateTimeField(blank=True, help_text='Last observation timestamp', null=True),
        ),
    ]
