# Generated by Django 5.2.8 on 2025-11-18 01:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0005_location_current_conditions_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='is_favorite',
            field=models.BooleanField(default=False, help_text='Mark as favorite location'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['is_favorite'], name='weather_loc_is_favo_42cf0f_idx'),
        ),
    ]
