# Generated by Django 5.1.5 on 2025-11-18 17:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0006_location_is_favorite_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['-is_current_location', '-is_favorite', 'display_order', 'name'], 'verbose_name': 'Location', 'verbose_name_plural': 'Locations'},
        ),
        migrations.AddField(
            model_name='location',
            name='is_current_location',
            field=models.BooleanField(default=False, help_text='Mark as current/home location'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['is_current_location'], name='weather_loc_is_curr_ac99da_idx'),
        ),
    ]
