# Generated by Django 5.1.5 on 2025-11-18 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0006_location_location_type'),
        ('weather', '0007_alter_location_options_location_is_current_location_and_more'),
    ]

    operations = [
    ]
