# Generated by Django 5.1.5 on 2025-11-18 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0008_merge_20251118_1230'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['-is_current_location', 'display_order', 'name'], 'verbose_name': 'Location', 'verbose_name_plural': 'Locations'},
        ),
        migrations.RemoveIndex(
            model_name='forecastrequest',
            name='weather_for_user_id_195b65_idx',
        ),
        migrations.RemoveIndex(
            model_name='location',
            name='weather_loc_created_e2f3b7_idx',
        ),
        migrations.RemoveField(
            model_name='forecastrequest',
            name='user',
        ),
        migrations.RemoveField(
            model_name='location',
            name='created_by',
        ),
        migrations.AddField(
            model_name='forecastrequest',
            name='session_key',
            field=models.CharField(blank=True, help_text='Session key for anonymous users', max_length=40),
        ),
        migrations.AddIndex(
            model_name='forecastrequest',
            index=models.Index(fields=['session_key', 'created_at'], name='weather_for_session_e4a9b1_idx'),
        ),
    ]
