# Generated by Django 5.1.5 on 2025-11-18 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0009_remove_user_authentication'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='is_enabled',
            field=models.BooleanField(default=True, help_text='Whether this location is enabled and visible on other pages'),
        ),
    ]
