# Generated by Django 5.1.5 on 2025-11-20 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0010_location_is_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='current_apparent_temp',
            field=models.IntegerField(blank=True, help_text='Current apparent temperature (feels like)', null=True),
        ),
    ]
