# Generated by Django 5.1.5 on 2026-01-19 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0012_location_current_wind_gust'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='avg_high_temp',
            field=models.FloatField(blank=True, help_text='Average high temperature for this location (°F)', null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='avg_low_temp',
            field=models.FloatField(blank=True, help_text='Average low temperature for this location (°F)', null=True),
        ),
    ]
