# Generated by Django 5.2.8 on 2026-02-10 21:28

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0014_location_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='forecastperiod',
            name='last_api_update',
            field=models.DateTimeField(blank=True, help_text='Timestamp when this forecast was last fetched from API', null=True),
        ),
        migrations.CreateModel(
            name='CurrentConditions',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('temperature', models.IntegerField(help_text='Current temperature in degrees Fahrenheit', validators=[django.core.validators.MinValueValidator(-50), django.core.validators.MaxValueValidator(150)])),
                ('feels_like_temperature', models.IntegerField(blank=True, help_text='Current apparent/feels-like temperature', null=True, validators=[django.core.validators.MinValueValidator(-50), django.core.validators.MaxValueValidator(150)])),
                ('condition', models.CharField(help_text='Current weather condition description', max_length=200)),
                ('wind_speed', models.IntegerField(help_text='Wind speed in mph', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(200)])),
                ('wind_direction', models.CharField(blank=True, help_text='Wind direction (e.g., NE, SW)', max_length=10)),
                ('wind_gust', models.IntegerField(blank=True, help_text='Wind gust speed in mph', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(200)])),
                ('humidity', models.IntegerField(help_text='Relative humidity as percentage', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('precipitation', models.FloatField(blank=True, help_text='Precipitation amount in inches', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('pressure', models.FloatField(blank=True, help_text='Barometric pressure in mb', null=True)),
                ('visibility', models.FloatField(blank=True, help_text='Visibility in miles', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('uv_index', models.IntegerField(blank=True, help_text='UV index value', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('last_observation_time', models.DateTimeField(help_text='Timestamp of the observation/API response')),
                ('raw_data', models.JSONField(blank=True, help_text='Raw API response data', null=True)),
                ('location', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='current_conditions_cache', to='weather.location')),
            ],
            options={
                'verbose_name': 'Current Conditions',
                'verbose_name_plural': 'Current Conditions',
                'ordering': ['-last_observation_time'],
                'indexes': [models.Index(fields=['location'], name='weather_cur_locatio_b8982c_idx'), models.Index(fields=['last_observation_time'], name='weather_cur_last_ob_457032_idx'), models.Index(fields=['updated_at'], name='weather_cur_updated_238b3f_idx')],
            },
        ),
    ]
