# Generated by Django 6.0.8 on 2026-09-01 16:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0018_rename_weather_cust_owner_loca_4c174d_idx_weather_cus_owner_i_091ca9_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeleconnectionObservation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('index_key', models.CharField(choices=[('oni', 'Oceanic Nino Index'), ('ao', 'Arctic Oscillation'), ('nao', 'North Atlantic Oscillation'), ('pna', 'Pacific-North American Pattern'), ('epo', 'East Pacific Oscillation'), ('wpo', 'West Pacific Oscillation')], max_length=12)),
                ('observation_date', models.DateField()),
                ('value', models.FloatField()),
                ('source_url', models.URLField(max_length=500)),
                ('source_metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['index_key', 'observation_date'],
                'indexes': [models.Index(fields=['index_key', 'observation_date'], name='weather_tel_index_k_9b2f79_idx')],
                'constraints': [models.UniqueConstraint(fields=('index_key', 'observation_date'), name='unique_teleconnection_index_date')],
            },
        ),
        migrations.CreateModel(
            name='HistoricalWeatherObservation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('observation_date', models.DateField()),
                ('source_kind', models.CharField(choices=[('ncei_station', 'NCEI station observation'), ('reanalysis', 'Reanalysis fallback')], max_length=20)),
                ('source_identifier', models.CharField(blank=True, max_length=100)),
                ('source_url', models.URLField(blank=True, max_length=500)),
                ('high_temperature', models.FloatField(blank=True, null=True)),
                ('low_temperature', models.FloatField(blank=True, null=True)),
                ('mean_temperature', models.FloatField(blank=True, null=True)),
                ('precipitation', models.FloatField(blank=True, null=True)),
                ('wind_speed', models.FloatField(blank=True, null=True)),
                ('snowfall', models.FloatField(blank=True, null=True)),
                ('source_metadata', models.JSONField(blank=True, default=dict)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historical_weather_observations', to='weather.location')),
            ],
            options={
                'ordering': ['location', 'observation_date', 'source_kind'],
                'indexes': [models.Index(fields=['location', 'observation_date'], name='weather_his_locatio_93d984_idx'), models.Index(fields=['source_kind', 'observation_date'], name='weather_his_source__502013_idx')],
                'constraints': [models.UniqueConstraint(fields=('location', 'observation_date', 'source_kind'), name='unique_historical_weather_location_date_source')],
            },
        ),
    ]
